repos:
  - repo: local
    hooks:
      - id: oxlint-oxfmt
        name: oxlint and oxfmt
        entry: ./scripts/pre-commit.sh
        language: script
        types: [ts, tsx, json]
        files: \.(json|ts|tsx|md)$
        pass_filenames: false
